import type {
  Boss,
  Chapter,
  ContentQuestion,
  KnowledgeNode,
  Milestone,
} from "@knowgate/domain";

export const gradeWorld = {
  id: "math.g4",
  contentVersion: "2026.09.20.1",
  subjectId: "math",
  grade: 4,
  name: "四年级 · 分数群岛",
  totalStages: 10,
};

export const knowledgeNodes: KnowledgeNode[] = [
  {
    id: "math.fractions_decimals.fraction_meaning",
    name: "分数意义与等值分数",
    domain: "分数、小数与比例",
    stage: "g3-g4",
    prerequisites: ["math.arithmetic.division_inverse"],
    mastery: [
      "能从整体和部分理解分数",
      "能识别分数单位",
      "能判断并找出等值分数",
    ],
  },
  {
    id: "math.arithmetic.division_inverse",
    name: "除法、余数与乘除互逆",
    domain: "四则运算",
    stage: "g3",
    prerequisites: ["math.arithmetic.multiplication_table"],
    mastery: ["能用乘法验算除法", "能理解余数意义"],
  },
  {
    id: "math.fractions_decimals.fraction_operations",
    name: "分数比较与四则运算",
    domain: "分数、小数与比例",
    stage: "g4-g5",
    prerequisites: ["math.fractions_decimals.fraction_meaning"],
    mastery: ["能比较分数大小", "能完成分数基本运算"],
  },
];

const fractionBar = (
  total: number,
  active: number,
  compareTo?: number,
): ContentQuestion["visual"] => ({
  kind: "fraction-bar",
  total,
  active,
  compareTo,
});

export const chapters: Chapter[] = [
  {
    id: "chapter.fraction.parts",
    milestoneId: "math.g4.milestone.01",
    stageNo: 1,
    title: "整体被分成几份",
    summary: "从公平分物出发，认识分母和分子表示什么。",
    estimatedMinutes: 5,
    nodeIds: ["math.fractions_decimals.fraction_meaning"],
    steps: [
      {
        id: "parts.hook",
        phase: "hook",
        title: "四块一样大的巧克力",
        body: "小满拿走其中一块。要准确说清她拿了多少，不能只说“一块”，还要说明全部被分成了几块。",
        visual: fractionBar(4, 1, 1),
      },
      {
        id: "parts.concept",
        phase: "concept",
        title: "分母看总数，分子看取走数",
        body: "整体被平均分成 4 份，取走 1 份，就写作 1/4。分母 4 表示平均分成的份数，分子 1 表示取走的份数。",
        visual: fractionBar(4, 1, 1),
      },
      {
        id: "parts.example",
        phase: "example",
        title: "先看整体，再数部分",
        body: "同一条长条平均分成 4 份，涂色 2 份就是 2/4。先确认“平均分成几份”，再数“涂了几份”。",
        visual: fractionBar(4, 2, 2),
      },
      {
        id: "parts.guided",
        phase: "guided",
        title: "跟着数一数",
        body: "先看总共有几份，再看涂色有几份。",
        visual: fractionBar(6, 3, 3),
        question: {
          id: "item.fraction.parts.guided",
          nodeId: "math.fractions_decimals.fraction_meaning",
          kind: "identify",
          prompt: "图中涂色部分表示哪个分数？",
          options: ["3/6", "6/3", "3/3"],
          answerIndex: 0,
          explanation: "整体平均分成 6 份，涂色 3 份，所以是 3/6。",
          timeLimitSec: 30,
          damage: 1,
          visual: fractionBar(6, 3),
        },
      },
      {
        id: "parts.practice",
        phase: "practice",
        title: "独立判断",
        body: "注意分母与分子的顺序。",
        visual: fractionBar(5, 2),
        question: {
          id: "item.fraction.parts.practice",
          nodeId: "math.fractions_decimals.fraction_meaning",
          kind: "judge",
          prompt: "一个整体平均分成 5 份，取走 2 份，可以写成 2/5。",
          options: ["正确", "错误"],
          answerIndex: 0,
          explanation: "分母表示平均分成 5 份，分子表示取走 2 份。",
          timeLimitSec: 30,
          damage: 1,
          visual: fractionBar(5, 2),
        },
      },
      {
        id: "parts.quiz",
        phase: "quiz",
        title: "章节短测",
        body: "答对这一题，本章的学习证据就记录完成。",
        visual: fractionBar(8, 5),
        question: {
          id: "item.fraction.parts.quiz",
          nodeId: "math.fractions_decimals.fraction_meaning",
          kind: "apply",
          prompt: "图中涂色部分表示哪个分数？",
          options: ["5/8", "8/5", "3/8"],
          answerIndex: 0,
          explanation: "总共有 8 份，涂色 5 份，因此是 5/8。",
          timeLimitSec: 45,
          damage: 2,
          visual: fractionBar(8, 5),
        },
      },
    ],
  },
  {
    id: "chapter.fraction.units",
    milestoneId: "math.g4.milestone.01",
    stageNo: 2,
    title: "分数单位与大小",
    summary: "理解同样大小的整体中，分母越大，每一份越小。",
    estimatedMinutes: 6,
    nodeIds: ["math.fractions_decimals.fraction_meaning"],
    steps: [
      {
        id: "units.hook",
        phase: "hook",
        title: "谁分到的更大",
        body: "两个同样大的披萨，一个平均切成 3 份，一个平均切成 6 份。都拿 1 份，哪一份更大？",
        visual: fractionBar(3, 1, 1),
      },
      {
        id: "units.concept",
        phase: "concept",
        title: "分母越大，每份越小",
        body: "1/3 表示从 3 份中拿 1 份，1/6 表示从 6 份中拿 1 份。整体相同且每份同样大时，1/3 大于 1/6。",
        visual: fractionBar(3, 1, 1),
      },
      {
        id: "units.example",
        phase: "example",
        title: "用同一条长条比较",
        body: "同一条长条分成 4 份时，每份较长；分成 8 份时，每份较短。所以分子都为 1 时，分母小的分数更大。",
        visual: fractionBar(8, 1, 1),
      },
      {
        id: "units.guided",
        phase: "guided",
        title: "选择更大的一份",
        body: "两个分数的整体大小相同。",
        visual: fractionBar(5, 1, 1),
        question: {
          id: "item.fraction.units.guided",
          nodeId: "math.fractions_decimals.fraction_meaning",
          kind: "judge",
          prompt: "在同样大的整体中，1/5 比 1/8 大。",
          options: ["正确", "错误"],
          answerIndex: 0,
          explanation: "平均分成 5 份时，每份比平均分成 8 份时更大。",
          timeLimitSec: 30,
          damage: 1,
        },
      },
      {
        id: "units.practice",
        phase: "practice",
        title: "独立比较",
        body: "先确认整体一样大，再比较每一份的大小。",
        visual: fractionBar(10, 1, 1),
        question: {
          id: "item.fraction.units.practice",
          nodeId: "math.fractions_decimals.fraction_meaning",
          kind: "apply",
          prompt: "下面哪个分数最大？",
          options: ["1/10", "1/6", "1/3"],
          answerIndex: 2,
          explanation: "分子都为 1 时，分母越小，分数越大。",
          timeLimitSec: 40,
          damage: 2,
        },
      },
      {
        id: "units.quiz",
        phase: "quiz",
        title: "章节短测",
        body: "用“每份大小”解释你的判断。",
        question: {
          id: "item.fraction.units.quiz",
          nodeId: "math.fractions_decimals.fraction_meaning",
          kind: "apply",
          prompt: "同样大的两个蛋糕，小红吃 1/4，小刚吃 1/7。谁吃得更多？",
          options: ["小红", "小刚", "一样多"],
          answerIndex: 0,
          explanation: "整体相同时，1/4 的每一份大于 1/7 的每一份。",
          timeLimitSec: 45,
          damage: 2,
        },
      },
    ],
  },
  {
    id: "chapter.fraction.equivalent",
    milestoneId: "math.g4.milestone.01",
    stageNo: 3,
    title: "找出等值分数",
    summary: "通过继续平均分，理解不同分数可以表示同样的大小。",
    estimatedMinutes: 6,
    nodeIds: ["math.fractions_decimals.fraction_meaning"],
    steps: [
      {
        id: "equivalent.hook",
        phase: "hook",
        title: "半个饼，也能写成两份四分之一",
        body: "把一个饼平均分成 2 份，取 1 份是 1/2。如果把每一份再平均切成 2 份，就得到 2 个 1/4。",
        visual: fractionBar(4, 2, 2),
      },
      {
        id: "equivalent.concept",
        phase: "concept",
        title: "大小相同，写法可以不同",
        body: "1/2 和 2/4 覆盖同样大的区域，所以它们相等。找等值分数时，分子和分母要同时乘或除以同一个非零数。",
        visual: fractionBar(4, 2, 2),
      },
      {
        id: "equivalent.example",
        phase: "example",
        title: "把每一份继续平均分",
        body: "1/2 的分子分母都乘 3，得到 3/6。图中 3/6 与 1/2 覆盖的区域一样大，因此 1/2 = 3/6。",
        visual: fractionBar(6, 3, 3),
      },
      {
        id: "equivalent.guided",
        phase: "guided",
        title: "找出后的等值分数",
        body: "分子分母同时乘 2。",
        visual: fractionBar(4, 2, 2),
        question: {
          id: "item.fraction.equivalent.guided",
          nodeId: "math.fractions_decimals.fraction_meaning",
          kind: "apply",
          prompt: "1/3 的分子分母同时乘 2，得到哪个分数？",
          options: ["2/6", "2/3", "3/6"],
          answerIndex: 0,
          explanation: "1×2=2，3×2=6，所以得到 2/6。",
          timeLimitSec: 35,
          damage: 1,
        },
      },
      {
        id: "equivalent.practice",
        phase: "practice",
        title: "独立找等值分数",
        body: "先看分子分母同时乘了哪个数。",
        visual: fractionBar(8, 4, 4),
        question: {
          id: "item.fraction.equivalent.practice",
          nodeId: "math.fractions_decimals.fraction_meaning",
          kind: "apply",
          prompt: "下面哪个分数与 1/4 相等？",
          options: ["2/4", "2/8", "4/4"],
          answerIndex: 1,
          explanation: "1/4 的分子分母同时乘 2，得到 2/8。",
          timeLimitSec: 40,
          damage: 2,
        },
      },
      {
        id: "equivalent.quiz",
        phase: "quiz",
        title: "章节短测",
        body: "用图中覆盖区域验证你的答案。",
        visual: fractionBar(6, 2, 2),
        question: {
          id: "item.fraction.equivalent.quiz",
          nodeId: "math.fractions_decimals.fraction_meaning",
          kind: "transfer",
          prompt: "与 2/6 相等的分数是哪一个？",
          options: ["1/3", "2/3", "1/6"],
          answerIndex: 0,
          explanation: "2/6 的分子分母同时除以 2，得到 1/3。",
          timeLimitSec: 45,
          damage: 2,
          visual: fractionBar(6, 2, 2),
        },
      },
    ],
  },
];

export const milestones: Milestone[] = [
  {
    id: "math.g4.milestone.01",
    stageNo: 1,
    name: "分数裂谷",
    theme: "看懂部分与整体",
    summary: "辨认分数、比较同分子的分数，并找出等值分数。",
    nodeIds: ["math.fractions_decimals.fraction_meaning"],
    chapterIds: chapters.map((chapter) => chapter.id),
    bossId: "boss.math.fraction_warden",
  },
  {
    id: "math.g4.milestone.02",
    stageNo: 2,
    name: "等值回廊",
    theme: "在不同写法间穿梭",
    summary: "继续扩展分数意义与等值关系。",
    nodeIds: ["math.fractions_decimals.fraction_meaning"],
    chapterIds: [],
    bossId: "boss.math.equivalent_keeper",
  },
  {
    id: "math.g4.milestone.03",
    stageNo: 3,
    name: "比较高塔",
    theme: "判断分数大小",
    summary: "比较不同分子和分母的分数。",
    nodeIds: ["math.fractions_decimals.fraction_operations"],
    chapterIds: [],
    bossId: "boss.math.compare_tower",
  },
  {
    id: "math.g4.milestone.04",
    stageNo: 4,
    name: "小数渡口",
    theme: "连接分数与小数",
    summary: "理解小数位值并完成基础互换。",
    nodeIds: ["math.fractions_decimals.decimal_meaning"],
    chapterIds: [],
    bossId: "boss.math.decimal_ferry",
  },
  {
    id: "math.g4.milestone.05",
    stageNo: 5,
    name: "精度工坊",
    theme: "进行小数运算",
    summary: "完成小数加减并估计结果。",
    nodeIds: ["math.fractions_decimals.decimal_operations"],
    chapterIds: [],
    bossId: "boss.math.precision_engineer",
  },
  {
    id: "math.g4.milestone.06",
    stageNo: 6,
    name: "图形测场",
    theme: "理解图形的性质",
    summary: "识别平行、垂直和常见图形关系。",
    nodeIds: ["math.geometry.shapes_relations"],
    chapterIds: [],
    bossId: "boss.math.shape_surveyor",
  },
  {
    id: "math.g4.milestone.07",
    stageNo: 7,
    name: "数据棱镜",
    theme: "读取统计信息",
    summary: "从统计图与表格中提取信息。",
    nodeIds: ["math.data_probability.charts"],
    chapterIds: [],
    bossId: "boss.math.data_prism",
  },
  {
    id: "math.g4.milestone.08",
    stageNo: 8,
    name: "运算中枢",
    theme: "掌握运算顺序",
    summary: "使用括号并按顺序完成混合运算。",
    nodeIds: ["math.arithmetic.mixed_operations"],
    chapterIds: [],
    bossId: "boss.math.operation_core",
  },
  {
    id: "math.g4.milestone.09",
    stageNo: 9,
    name: "情境枢纽",
    theme: "把题意变成算式",
    summary: "提取数量关系并完成多步骤问题。",
    nodeIds: ["math.modeling.word_problem_models"],
    chapterIds: [],
    bossId: "boss.math.context_hub",
  },
  {
    id: "math.g4.milestone.10",
    stageNo: 10,
    name: "终局演算",
    theme: "综合迁移",
    summary: "连接本世界核心能力并完成终结挑战。",
    nodeIds: ["math.modeling.multi_step_problems"],
    chapterIds: [],
    bossId: "boss.math.final_algorithm",
  },
];

export const bossQuestions: ContentQuestion[] = [
  {
    id: "item.fraction.boss.01",
    nodeId: "math.fractions_decimals.fraction_meaning",
    kind: "identify",
    prompt: "一个整体平均分成 7 份，取走 3 份。下面哪个分数正确？",
    options: ["3/7", "7/3", "3/4"],
    answerIndex: 0,
    explanation: "分母表示平均分成 7 份，分子表示取走 3 份。",
    timeLimitSec: 5,
    damage: 1,
    visual: fractionBar(7, 3),
  },
  {
    id: "item.fraction.boss.02",
    nodeId: "math.fractions_decimals.fraction_meaning",
    kind: "identify",
    prompt: "图中涂色部分表示哪个分数？",
    options: ["2/3", "3/2", "1/3"],
    answerIndex: 2,
    explanation: "整体平均分成 3 份，涂色 1 份。",
    timeLimitSec: 5,
    damage: 1,
    visual: fractionBar(3, 1),
  },
  {
    id: "item.fraction.boss.03",
    nodeId: "math.fractions_decimals.fraction_meaning",
    kind: "judge",
    prompt: "在同样大的整体中，1/4 大于 1/9。",
    options: ["正确", "错误"],
    answerIndex: 0,
    explanation: "分子相同时，分母越小，每一份越大。",
    timeLimitSec: 5,
    damage: 1,
  },
  {
    id: "item.fraction.boss.04",
    nodeId: "math.fractions_decimals.fraction_meaning",
    kind: "judge",
    prompt: "1/2 和 2/4 表示同样的大小。",
    options: ["正确", "错误"],
    answerIndex: 0,
    explanation: "1/2 的分子和分母同时乘 2，得到 2/4。",
    timeLimitSec: 5,
    damage: 1,
  },
  {
    id: "item.fraction.boss.05",
    nodeId: "math.fractions_decimals.fraction_meaning",
    kind: "apply",
    prompt: "下面哪个分数与 3/5 相等？",
    options: ["6/10", "5/6", "3/10"],
    answerIndex: 0,
    explanation: "3/5 的分子和分母同时乘 2，得到 6/10。",
    timeLimitSec: 30,
    damage: 2,
  },
  {
    id: "item.fraction.boss.06",
    nodeId: "math.fractions_decimals.fraction_meaning",
    kind: "apply",
    prompt: "一个整体平均分成 9 份，取走 4 份。对应分数是哪一个？",
    options: ["9/4", "4/9", "4/5"],
    answerIndex: 1,
    explanation: "总份数是分母 9，取走份数是分子 4。",
    timeLimitSec: 30,
    damage: 2,
  },
  {
    id: "item.fraction.boss.07",
    nodeId: "math.fractions_decimals.fraction_meaning",
    kind: "apply",
    prompt: "同样大的果汁，A 杯喝了 1/6，B 杯喝了 1/3。哪杯喝得更多？",
    options: ["A 杯", "B 杯", "一样多"],
    answerIndex: 1,
    explanation: "整体相同时，1/3 大于 1/6。",
    timeLimitSec: 45,
    damage: 2,
  },
  {
    id: "item.fraction.boss.08",
    nodeId: "math.fractions_decimals.fraction_meaning",
    kind: "transfer",
    prompt: "哪一组分数相等？",
    options: ["2/3 和 4/6", "2/3 和 3/4", "4/8 和 1/4"],
    answerIndex: 0,
    explanation: "2/3 的分子和分母同时乘 2，得到 4/6。",
    timeLimitSec: 45,
    damage: 2,
  },
  {
    id: "item.fraction.boss.09",
    nodeId: "math.fractions_decimals.fraction_meaning",
    kind: "transfer",
    prompt: "把 6/8 的分子和分母同时除以 2，得到哪个分数？",
    options: ["3/4", "2/4", "4/6"],
    answerIndex: 0,
    explanation: "6÷2=3，8÷2=4，所以得到 3/4。",
    timeLimitSec: 60,
    damage: 2,
  },
  {
    id: "item.fraction.boss.10",
    nodeId: "math.fractions_decimals.fraction_meaning",
    kind: "transfer",
    prompt: "一条长条先平均分成 4 份，再把每份平均分成 2 份，总共得到多少份？",
    options: ["6 份", "8 份", "10 份"],
    answerIndex: 1,
    explanation: "4 份中的每一份再分成 2 份，总共 4×2=8 份。",
    timeLimitSec: 60,
    damage: 2,
  },
  {
    id: "item.fraction.boss.decisive",
    nodeId: "math.fractions_decimals.fraction_meaning",
    kind: "decisive",
    prompt: "决胜题：下面说法正确的是哪一个？",
    options: [
      "1/2 = 4/8，因为分子分母同时乘 4",
      "1/2 = 2/3，因为分母增加了 1",
      "1/2 = 1/4，因为整体被继续细分",
    ],
    answerIndex: 0,
    explanation: "1/2 的分子和分母同时乘 4，得到 4/8，大小不变。",
    timeLimitSec: 120,
    damage: 3,
  },
];

export const bosses: Boss[] = [
  {
    id: "boss.math.fraction_warden",
    milestoneId: "math.g4.milestone.01",
    name: "分数守卫",
    epithet: "裂谷的守门者",
    hp: 9,
    initialDistance: 5,
    questionIds: bossQuestions.map((question) => question.id),
  },
];

export const firstMilestone = milestones[0];
export const firstBoss = bosses[0];

export function getMilestone(milestoneId: string) {
  return milestones.find((milestone) => milestone.id === milestoneId);
}

export function getChapter(chapterId: string) {
  return chapters.find((chapter) => chapter.id === chapterId);
}

export function getBoss(bossId: string) {
  return bosses.find((boss) => boss.id === bossId);
}

export function getNode(nodeId: string) {
  return knowledgeNodes.find((node) => node.id === nodeId);
}
